<template>
      <div class="table-row">
        <div class="table-col text-left">
          <span class="loadingSpan"></span>
        </div>
        <div class="table-col text-left">
          <span class="loadingSpan"></span>
        </div>
        <div class="table-col text-left">
          <span class="loadingSpan"></span>
        </div>
        <div class="table-col text-left">
          <span class="loadingSpan"></span>
        </div>
      </div>
</template>

<script>
export default {

  name: 'tableLoading',
};
</script>

<style lang="css" scoped>
.loadingSpan {
  display:block;
  padding:0.75em;
  background:#f3f3f3;
  -webkit-animation: blink-1 0.5s ease-in-out infinite both;
          animation: blink-1 0.5s ease-in-out infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-4-8 15:11:37
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation blink-1
 * ----------------------------------------
 */
@-webkit-keyframes blink-1 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0;
  }
}
@keyframes blink-1 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0;
  }
}
</style>
